-- Insert initial products
INSERT INTO products (id, name, price, description, image, images, category, rating, reviews, stock, featured, specs, productReviews, questions)
VALUES 
('1', 'Aether Pods Pro', 299, 'Next-generation spatial audio with neural noise cancellation. Experience sound like never before with our proprietary bio-acoustic drivers.', 'https://picsum.photos/seed/audio1/800/800', ARRAY['https://picsum.photos/seed/audio1/800/800', 'https://picsum.photos/seed/audio2/800/800', 'https://picsum.photos/seed/audio3/800/800'], 'Audio', 4.9, 1240, 45, true, '{"Battery Life": "40 Hours", "Connectivity": "Bluetooth 5.3", "Water Resistance": "IPX7", "Weight": "5.4g per bud"}', '[{"id": "rev-1", "userId": "user-1", "userName": "Sarah Jenkins", "rating": 5, "comment": "Absolutely incredible sound quality! The noise cancellation is the best I have ever experienced.", "createdAt": "2026-02-15T10:00:00Z"}, {"id": "rev-2", "userId": "user-2", "userName": "Michael Chen", "rating": 4, "comment": "Great battery life and very comfortable for long sessions. The bass is a bit punchy but clear.", "createdAt": "2026-02-20T14:30:00Z"}]', '[{"id": "q-1", "userId": "user-3", "userName": "David Miller", "text": "Does it support multi-point connection?", "answer": "Yes, the Aether Pods Pro support simultaneous connection to two devices.", "createdAt": "2026-02-10T09:00:00Z"}, {"id": "q-2", "userId": "user-4", "userName": "Emily Rose", "text": "How long does it take to fully charge the case?", "answer": "It takes approximately 1.5 hours to fully charge the case via USB-C.", "createdAt": "2026-02-25T16:45:00Z"}]'),
('2', 'Quantum Core Laptop', 2499, 'The ultimate workstation for creators. Powered by the M3-X Neural Engine and a 120Hz Liquid Retina XDR display.', 'https://picsum.photos/seed/laptop1/800/800', ARRAY['https://picsum.photos/seed/laptop1/800/800', 'https://picsum.photos/seed/laptop2/800/800'], 'Computing', 4.8, 850, 12, true, '{"Processor": "Quantum X1", "RAM": "64GB Unified", "Storage": "2TB SSD", "Display": "16\\" OLED 120Hz"}', '[]', '[]'),
('3', 'Horizon Watch Ultra', 799, 'A rugged, capable timepiece designed for the extremes. Titanium casing and sapphire crystal glass.', 'https://picsum.photos/seed/watch1/800/800', ARRAY['https://picsum.photos/seed/watch1/800/800', 'https://picsum.photos/seed/watch2/800/800'], 'Wearables', 4.7, 2100, 88, true, '{"Material": "Aerospace Titanium", "Battery": "72 Hours", "Sensors": "ECG, SpO2, Temp", "Depth": "100m Water Resistant"}', '[]', '[]'),
('4', 'Nebula Smart Hub', 199, 'Control your entire ecosystem with a simple voice command or gesture. The brain of your futuristic home.', 'https://picsum.photos/seed/home1/800/800', ARRAY['https://picsum.photos/seed/home1/800/800'], 'Smart Home', 4.6, 450, 156, false, '{"Display": "7\\" Touchscreen", "Speakers": "Dual 10W Drivers", "Connectivity": "Matter, Thread, Zigbee", "Camera": "12MP Wide Angle"}', '[]', '[]'),
('5', 'Sonic Beam Soundbar', 599, 'Immersive Dolby Atmos sound that fills the room. Sleek, minimalist design that blends into any interior.', 'https://picsum.photos/seed/audio4/800/800', ARRAY['https://picsum.photos/seed/audio4/800/800'], 'Audio', 4.8, 320, 24, false, '{"Channels": "7.1.2 Surround", "Power": "500W Peak", "Inputs": "HDMI eARC, Optical", "Wireless": "AirPlay 2, Cast"}', '[]', '[]'),
('6', 'Titan Desktop Pro', 3999, 'Unmatched performance for heavy rendering and data processing. The pinnacle of desktop computing.', 'https://picsum.photos/seed/pc1/800/800', ARRAY['https://picsum.photos/seed/pc1/800/800'], 'Computing', 4.9, 120, 5, false, '{"GPU": "RTX 5090 Ti", "CPU": "Threadripper 7000", "Cooling": "Liquid Nitrogen Loop", "Power": "1500W Platinum"}', '[]', '[]')
ON CONFLICT (id) DO NOTHING;

-- Insert default admin user
INSERT INTO profiles (id, name, email, password, role, joinedAt)
VALUES ('admin-1', 'Admin User', 'admin@example.com', 'admin', 'admin', NOW())
ON CONFLICT (id) DO NOTHING;
